title: MICROCMPT
theme: jekyll-theme-cayman
url: https://www.microcmpt.io
description: 微服务架构解决方案，让微服务落地更容易，更轻量级
highlighter: rogue
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
navs:
  -
    href: /
label: 首页