title: MICROCMPT
theme: jekyll-theme-architect
url: https://microcmpt.github.io
description: Microservice architecture solutions make it easier and lighter to implement.
highlighter: rogue
layout: post
